project:
  type: website
  output-dir: docs

website:
  title: "Denise Chang"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - contact.qmd
      - text: "CV"
        href: cv-Denise_Chang.pdf


format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

