---
title: "Denise Chang"
---

Hi! My name is Denise and I am a second year student at the University of Toronto pursuing a Bachelor of Science in Mathematics and Statistics.

I am interested in a wide range of topics, but my heart goes to the study of number theory and of arithmetic geometry.

Outside of lectures, you can mostly find me around campus, engaging in all sorts of extracurricular activities. My main commitment this year is being the Communications Director at VUSAC's Commuter Commission. I've met the greatest people there and loved every part of my experience working with this team.

I also enjoy doing volunteer work. During the academic season, I volunteer at the Math Outreach Office by helping out with invigilating, processing and marking competitions, such as the COMC and the Kangaroo Contest. I am also a volunteer at the Cat's Eye, a student lounge at Victoria College, where I get the chance to meet amazing people and host awesome events.

I have volunteered two summers in a row at Otakuthon, an anime and manga convention held annually in Montreal, Canada. In 2022 I was a general volunteer and in 2023 I was hired as a staff in the registration department. I am particularly proud of this last involvement since it was the first time I got involved with a community external to school, and it was a big step out of my comfort zone!
